# Generated by Django 4.2 on 2023-05-01 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "margin",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CURE", "Lék"),
                            ("MATERIAL", "Materiál"),
                            ("OTHER", "Ostatní"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "supplier_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("supplier", models.CharField(blank=True, max_length=200, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("ean", models.CharField(blank=True, max_length=50, null=True)),
                ("batch", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "units_in_stock",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "units_in_package",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "margin",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stock.stock",
                    ),
                ),
            ],
        ),
    ]
