# Generated by Django 4.2 on 2023-05-01 19:33

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("dog", "Pes"),
                            ("cat", "Kočka"),
                            ("rodent", "Hlodavec"),
                            ("bird", "Pták"),
                            ("horse", "Kůň"),
                            ("reptile", "Plaz"),
                            ("pig", "Prase"),
                            ("sheep", "Ovce"),
                            ("goat", "Koza"),
                            ("cow", "Kráva"),
                            ("other", "Jiné"),
                        ],
                        default="dog",
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Samec"),
                            ("female", "Samice"),
                            ("unknown", "Neznámé"),
                        ],
                        max_length=10,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("chip_number", models.CharField(blank=True, max_length=50)),
                ("chip_location", models.CharField(blank=True, max_length=50)),
                ("chip_application_date", models.DateField(blank=True, null=True)),
                ("passport_number", models.CharField(blank=True, max_length=50)),
                ("passport_issue_date", models.DateField(blank=True, null=True)),
                ("castration", models.BooleanField(default=False)),
                ("dead", models.BooleanField(default=False)),
                ("insured", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnimalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("closed", models.BooleanField(default=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="records.animal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
                ("house_number", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=10)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("company_name", models.CharField(blank=True, max_length=50)),
                ("ic", models.CharField(blank=True, max_length=20)),
                ("dic", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("record", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="records.animalcase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="records.owner",
            ),
        ),
    ]
