# Generated by Django 4.2 on 2023-04-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("dog", "Pes"),
                            ("cat", "Kočka"),
                            ("rodent", "Hlodavec"),
                            ("bird", "Pták"),
                            ("horse", "Kůň"),
                            ("reptile", "Plaz"),
                            ("pig", "Prase"),
                            ("sheep", "Ovce"),
                            ("goat", "Koza"),
                            ("cow", "Kráva"),
                            ("other", "Jiné"),
                        ],
                        default="dog",
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Samec"),
                            ("female", "Samice"),
                            ("unknown", "Neznámé"),
                        ],
                        max_length=10,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("chip_number", models.CharField(blank=True, max_length=50)),
                ("chip_location", models.CharField(blank=True, max_length=50)),
                ("chip_application_date", models.DateField(blank=True, null=True)),
                ("passport_number", models.CharField(blank=True, max_length=50)),
                ("passport_issue_date", models.DateField(blank=True, null=True)),
                ("castration", models.BooleanField(default=False)),
                ("dead", models.BooleanField(default=False)),
                ("insured", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="records.owner",
                    ),
                ),
            ],
        ),
    ]
