# Generated by Django 4.2 on 2023-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_visitprocedure"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
